version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pgms-db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgms-db-data:/var/lib/postgresql/data

volumes:
  pgms-db-data:
